DROP TABLE IF EXISTS tb_usuario_notificacao;
DROP TABLE IF EXISTS tb_notificacao;
DROP TABLE IF EXISTS tb_documento;
DROP TABLE IF EXISTS tb_usuario;
DROP TABLE IF EXISTS tb_user;


CREATE TABLE tb_user (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         login VARCHAR(255) NOT NULL UNIQUE,
                         senha VARCHAR(255) NOT NULL,
                         perfil VARCHAR(50) NOT NULL
);

INSERT INTO tb_user (login, senha, perfil)
VALUES ('admin','$2a$10$bvURj2qlBUU5CRTm8pBOLeQau1nYClU.5MB7H/uEWNfKxFfnpkryy', 'ADMINISTRADOR'),
('leitor','$2a$10$bvURj2qlBUU5CRTm8pBOLeQau1nYClU.5MB7H/uEWNfKxFfnpkryy', 'LEITOR');


CREATE TABLE tb_usuario (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(80) NOT NULL,
                            email VARCHAR(150) NOT NULL UNIQUE,
                            cpf VARCHAR(14) NOT NULL UNIQUE,
                            data_nascimento DATE,
                            aceite_termos BOOLEAN NOT NULL,
                            cidade VARCHAR(80),
                            estado VARCHAR(100),
                            pais VARCHAR(100),
                            foto BYTEA,
                            user_id BIGINT,

                            CONSTRAINT fk_usuario_user
                                FOREIGN KEY (user_id)
                                    REFERENCES tb_user(id)
);

INSERT INTO tb_usuario (
    nome, email, cpf, data_nascimento, aceite_termos, cidade, estado, pais, user_id)
VALUES ('Administrador','admin@email.com','64343764052','1990-01-01',
             TRUE,'Campinas','SP','Brasil',1),
       ('leitor','leitor@email.com','01803138009','1990-01-01',
        TRUE,'Campinas','SP','Brasil',2);


CREATE TABLE tb_notificacao (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                data_de_criacao TIMESTAMP NOT NULL,
                                notificacao VARCHAR(255) NOT NULL
);

INSERT INTO tb_notificacao (data_de_criacao, notificacao)
VALUES (CURRENT_TIMESTAMP, 'Bem-vindo ao sistema'),
       (CURRENT_TIMESTAMP, 'Alterado o termo gerais');


CREATE TABLE tb_usuario_notificacao (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        usuario_id BIGINT,
                                        notificacao_id BIGINT,
                                        visualizada BOOLEAN,
                                        data_leitura TIMESTAMP,

                                        CONSTRAINT fk_usuario_notificacao_usuario
                                            FOREIGN KEY (usuario_id)
                                                REFERENCES tb_usuario(id),

                                        CONSTRAINT fk_usuario_notificacao_notificacao
                                            FOREIGN KEY (notificacao_id)
                                                REFERENCES tb_notificacao(id)
);
INSERT INTO tb_usuario_notificacao (usuario_id, notificacao_id, visualizada, data_leitura)
VALUES
    (2, 1, false, null),
    (2, 2, true, null);


CREATE TABLE tb_documento (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              titulo VARCHAR(100) NOT NULL,
                              tipo_documento VARCHAR(50) NOT NULL,
                              conteudo TEXT NOT NULL,
                              ultima_alteracao TIMESTAMP
);

INSERT INTO tb_documento (
    titulo,
    tipo_documento,
    conteudo,
    ultima_alteracao
) VALUES (
             'Termos Gerais de Uso',
             'TERMOS_GERAIS_DE_USO',
             'Texto de teste para os termos de uso...',
             CURRENT_TIMESTAMP
         );